// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7sTROdgKfWHh5SRc0ku3j3Zig1T0ECw',
    appId: '1:989082461704:web:a06e49df983eb74ddc13bd',
    messagingSenderId: '989082461704',
    projectId: 'kerla-fatafat',
    authDomain: 'kerla-fatafat.firebaseapp.com',
    storageBucket: 'kerla-fatafat.firebasestorage.app',
    measurementId: 'G-C67Y0WYT6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjO6tsNqKaWpGRQhxm9ZDUiOzsCws_e9k',
    appId: '1:989082461704:android:4795bdbcb527380ddc13bd',
    messagingSenderId: '989082461704',
    projectId: 'kerla-fatafat',
    storageBucket: 'kerla-fatafat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFv6HkHsoYGRbiacKOu5UBkEPKe0U-Iu0',
    appId: '1:989082461704:ios:40bb3c946e2a1338dc13bd',
    messagingSenderId: '989082461704',
    projectId: 'kerla-fatafat',
    storageBucket: 'kerla-fatafat.firebasestorage.app',
    iosBundleId: 'com.example.kolkataFatafat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFv6HkHsoYGRbiacKOu5UBkEPKe0U-Iu0',
    appId: '1:989082461704:ios:40bb3c946e2a1338dc13bd',
    messagingSenderId: '989082461704',
    projectId: 'kerla-fatafat',
    storageBucket: 'kerla-fatafat.firebasestorage.app',
    iosBundleId: 'com.example.kolkataFatafat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj7sTROdgKfWHh5SRc0ku3j3Zig1T0ECw',
    appId: '1:989082461704:web:ec92222ea784d164dc13bd',
    messagingSenderId: '989082461704',
    projectId: 'kerla-fatafat',
    authDomain: 'kerla-fatafat.firebaseapp.com',
    storageBucket: 'kerla-fatafat.firebasestorage.app',
    measurementId: 'G-B58VCM03Y5',
  );
}
